= Rapport du groupe de réflexions Bureaux Doctorants

Brouillon.

== Origine du groupe et objectifs
Le Comité de Suivi de Thèse (CST) « deuxième année »  a écouté sept doctorants le 5 juin 2018. Il a été frappé par le fait que six doctorants parmi les sept entendus ont spontanément évoqué les problèmes liés à l’espace de travail qui leur est offert (ou ne leur est pas offert) par le LAMSADE. Voici un extrait de son rapport envoyé au Conseil du Laboratoire le 6 juin. 

[quote, Rapport du CST deuxième année, 6 juin 2018]
____
Une personne nous a indiqué qu’il y a souvent neuf personnes dans la pièce où on lui a offert un bureau. Une autre a mentionné qu’il fait souvent très chaud dans son bureau partagé (c’est bien sûr le cas de beaucoup de bureaux au LAMSADE, mais quand de nombreuses personnes partagent un bureau, c’est bien pire). Plusieurs ont fait remarquer qu’il est difficile de se concentrer dans une salle avec autant de monde (il y a de temps en temps des discussions entre occupants). Plusieurs choisissent plutôt, en solution de repli, d’aller à la bibliothèque. Une personne a fait remarquer que le problème est empiré par le fait que les bureaux partagés à destination des thésards sont parfois occupés par des stagiaires. Une personne en thèse CIFRE a fait remarquer que le LAMSADE ne lui offre pas de bureau, alors que la personne est priée de venir plusieurs jours par semaine au LAMSADE.
____

Le Conseil de Laboratoire a décidé le 12 juin de créer un groupe de réflexion sur l’affectation des bureaux des doctorants, avec pour mission de transmettre des propositions d’amélioration au Conseil. Ce rapport est le résultat du travail de ce groupe.

=== Objectifs
Ce rapport vise à proposer des pistes pour améliorer le confort de travail des doctorants au LAMSADE, entre autres mais pas seulement, en leur fournissant dans la mesure du possible plus d’espaces de travail.

== Situation actuelle
Les doctorants disposent actuellement des bureaux C602, C603 bis, C605, contenant respectivement 8, 9 et 9 places. Une salle supplémentaire est en train d’être mise à leur disposition en B214 (non encore occupée au moment de la rédaction de ce rapport), contenant 6 places. Cette salle n’est pas très appréciée des doctorants car elle est éloignée et située entre des salles de cours, donc avec du bruit alentours. Elle a cependant été insonorisée récemment. Le nombre de doctorants recensés sur le site du LAMSADE au moment de la rédaction de ce rapport est 44 (mais la liste est en cours de mise à jour).

Il semble que l’université s’apprête à fournir au LAMSADE un bureau supplémentaire en A525, dont nous nous servons dans la proposition ci-dessous.

== Propositions
En résumé, les propositions ci-dessous visent à :

* créer huit places supplémentaires pour les doctorants (portant le total à 39 places) ;
* utiliser la salle B214 comme salle de réunion (l’aspect bruit alentours étant moins handicapant pour cet usage) ;
* proposer quelques autres actions pour améliorer la situation des doctorants.

=== Places supplémentaires pour doctorants
Les propositions s’articulent autour de la généreuse proposition de certains membres du laboratoire de partager leur bureau pour améliorer la situation des doctorants. Qu’ils en soient ici remerciés.

* Remzy (actuellement en P647) et Jérôme Lang proposent de partager le bureau de Jérôme (P645).
* Juliette Rouchier et Yves (P621) proposent d’ajouter du mobilier dans leur bureau pour y accueillir un doctorant à temps plein, et de partager leurs deux places pour y accueillir deux doctorants (par exemple CIFRE) qui devront leur laisser la place quand Juliette et Yves sont présents (c-à-d moins d’un jour par semaine en moyenne).
* Laurent et Michail proposent d’ajouter du mobilier dans leur bureau (P622) pour y accueillir un doctorant (ou une autre personne) à temps plein.
* Florian Yger et Olivier Cailloux (P405ter) proposent d’accueillir un doctorant (qu’ils n’encadrent pas) à temps plein dans leur bureau.
* Ali (partageant actuellement le bureau de Remzi) accepte de déménager dans le bureau de Laurent et Michail (à condition de trouver une place pour ses livres).

Ces propositions s’assortissent de conditions.

* L’ensemble des propositions vient ensemble, elles ne tiennent pas nécessairement individuellement si d’autres ne se font pas.
* Il est proposé d’essayer la configuration proposée pendant une année, au terme de laquelle les proposants et les bénéficiaires feront le point et décideront ou non de la reconduction de l’expérience.
* Il faudra fournir aux personnes qui ont normalement droit à un bureau seul et qui acceptent de le partager un accès prioritaire à la salle des professeurs invités, pour qu’ils puissent continuer à accueillir des invités.
* Il faudra avoir à disposition une salle de réunion avec suffisamment de créneaux horaires disponibles pour compenser la difficulté accrue de tenir des réunions de travail lorsqu’on partage son bureau.

En meublant le P647 pour y accueillir quatre doctorants, on crée ainsi huit places supplémentaires pour les doctorants.

=== Salle de réunion
Les raisons de déployer les efforts nécessaires pour libérer une salle de réunion sont multiples.

* Disposer d’une salle de réunion serait très utile aux membres du LAMSADE (un sondage rapide organisé dans le groupe de réflexion fait ressortir ce besoin).
* C’est une condition nécessaire pour rendre effectives les propositions de partage présentées à la section précédente.
* Elle permettrait aux doctorants de s’isoler pour discuter de problèmes de recherche (entre eux ou avec leurs encadrants) et éviterait donc certaines discussions qui ont actuellement lieu dans le bureau doctorant lui-même, nuisant ainsi à la concentration de plusieurs autres personnes. (Le sondage indique que plusieurs doctorants utiliseraient cette possibilité.)

Le groupe de travail propose d’utiliser la salle B214 comme salle de réunion permanente. La salle en A525 qui devrait être prochainement attribuée au LAMSADE servirait à remplacer son usage actuel (c-à-d à accueillir des doctorants).

=== Planning en ligne pour salles de réunion
Il est demandé de débloquer un budget pour développer une application web permettant de réserver une salle de réunion facilement, de voir les plages horaires libres, et permettant aux membres d’indiquer leurs absences (pour ceux qui veulent bien qu’on utilise leur bureau comme salle de réunion).

* Outre la salle en B214 que ce rapport propose de libérer, nous avons régulièrement une ou plusieurs salles libres, en fonction des absences.
* Ces salles sont d’exploitation peu pratiques (y compris la B214) car il faut s’y rendre pour voir si elles sont libres ou pour inscrire son nom sur la feuille pour réserver (et faire éventuellement le tour de toutes les salles potentiellement disponibles, éventuellement suivi de l’invité avec qui on veut s’entretenir).
* Un budget pour un mois de développement à temps plein devrait permettre ce développement de façon confortable. On pourrait pour ce faire engager un de nos étudiants, si la loi le permet. Olivier Cailloux est volontaire pour l’encadrement.
* La valeur de marché d’une salle de réunion à Paris est de 600 € / mois. Le budget sera rapidement amorti, si on calcule à sa juste valeur l’apport d’une gestion commode de nos salles de réunions et le temps de notre personnel.

=== Propagation
Il est suggéré à la direction d’envoyer un appel officiel aux bonnes volontés : les volontaires prêts à créer une place dans leur bureau pour accueillir eux aussi un doctorant sont invités à se déclarer auprès de la direction.

=== Climatisation
D’ici à l’été prochain, il est proposé d’équiper les bureaux doctorants de climatiseurs mobiles.

=== Demande de modules supplémentaires à Paris-Dauphine
D’après les règles d’attribution officielles, le LAMSADE a semble-t-il droit à 44 modules, et en dispose en pratique de 42,5 (voir `Occupation.odt` sur OwnCloud). Ces totaux devraient être vérifiés par la direction et pourraient servir de base pour une (re-)négociation future.

=== Échange C602 et C603
Il est proposé d’étudier la possibilité de négocier avec la bibliothèque un échange de leur bureau C603 (très peu occupé) contre le bureau doctorant C602 (plus petit ?).

== Pistes postposées
D’autres pistes de réflexion ont été évoquées par le groupe. Elles sont listées ici sans ordre de priorité et sont éventuellement à conserver pour étude ultérieure.

* Créer des bureaux volants (mais difficile de se sentir chez soi : on n’ose pas pousser les affaires, on a peur de renverser, la personne n’a pas totalement libéré la place, on ne peut pas laisser ses papiers…)
* Suggérer de relâcher l’obligation de présence (mais légitimité, tact ?)
* Modifier proportion 1/5 entre doctorant et rang A dans règle d’attribution (mais à faire niveau Dauphine ?) ; faire dépendre des responsabilités ; échanger contre bourses, financements ; inciter à accueillir ses propres doctorants (mais mélange des genres malvenu ?)
* Aménager une vraie salle de réunion : projecteur, mobilier adéquat, pour groupe de lecture, mini séminaire…
* Bureaux volants pour membres peu présents (mais délicat, plutôt agir sur base volontaire ?)
* Comparer la place de nos doctorants avec celle des autres labos (mais ne pas procéder par envie ?)
* Suivre l’initiative casques anti-bruits
* Bureau commun CEREMADE et LAMSADE (problème de gestion commune ?)
* Solution créative pour troquer les bureaux en B2 (mais déjà tenté)

